name: squirrel
description: Create installable desktop apps
version: 0.2.1
homepage: https://github.com/jonathanmajh/squirrel-flutter

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  args: ^2.3.0
  flutter:
    sdk: flutter
  jinja: ^0.6.0
  package_config: ^2.0.2
  path: ^1.9.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
